spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/aushop_saas
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

# opcional: evitar exposição de stacktrace padrão
server:
  error:
    include-stacktrace: never

application:
  name: Aushop API
  version: "1.0"
  description: Documentação da API de gerenciamento de assinaturas
  contact:
    name: Equipe Aushop
    email: dev@example.com

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html